set_property PACKAGE_PIN H4 [get_ports clock]
set_property PACKAGE_PIN A5 [get_ports a]
set_property PACKAGE_PIN A4 [get_ports f]
set_property PACKAGE_PIN A10 [get_ports reset]
set_property PACKAGE_PIN B3 [get_ports g]
#set_property IOSTANDARD LVCMOS33 [get_ports {state[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports f]
set_property IOSTANDARD LVCMOS33 [get_ports a]
#set_property IOSTANDARD LVCMOS33 [get_ports {state[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports g]
set_property PULLDOWN true [get_ports f]
set_property PULLDOWN true [get_ports g]
set_property SLEW SLOW [get_ports g]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5}[get_ports clock]